

//Generated for platform: x64

// This code was generated by a script. Any changes made manually will be lost
// the next time this code is regenerated.
//
// It is edited by hand here regardless, because the T4 transform that generates it does not run
// in this build: local-build-no-vs makes the TextTemplating import conditional so the project
// builds without a full Visual Studio, and the transform goes with it. AssemblyInfo.tt carries
// the same values, so a machine that does run the transform produces this same file.

using System.Reflection;
using System.Resources;

// Compute version values


// General Information
[assembly: AssemblyTitle("mRemoteNG")]
[assembly: AssemblyDescription("Multi-Remote Next Generation Connection Manager")]
[assembly: AssemblyConfiguration("x64")]
[assembly: AssemblyCompany("Profi-KOM Ltd.")]
[assembly: AssemblyProduct("mRemoteNG Connection Manager")]
[assembly: AssemblyCopyright("(c) 2026 mRemoteNG")]
[assembly: AssemblyTrademark("Profi-KOM LTd.")]
[assembly: AssemblyCulture("")]

// Version information
//
// 1.80, and 3621 is gone from all three. It was a build counter inherited from upstream and it
// showed up in the About box, in the file properties, and - the one that mattered - inside
// AssemblyVersion.
//
// AssemblyVersion is shown to nobody: it is an identity, and .NET keys the per-user settings store
// by it, under %LOCALAPPDATA%\<company>\<app>_Url_<hash>\<version>\. Moving it on 2026-08-29
// started the application in an empty store - first-run questions again, a different monitor,
// because the window position lives there too - and that is why it sat frozen until now.
//
// Two things make it safe to move today:
//
// 1. Settings now survive a version change. They did not before: SettingsLoader upgraded exactly
//    one of the sixteen settings classes, so everything else came back at its defaults. It
//    upgrades all of them now, found by reflection rather than by a list the seventeenth would
//    drop out of.
//
// 2. The number goes UP. .NET migrates from the highest version below the current one, and version
//    parts are numbers, not text: 1.8 would have been below 1.78, so the old store would have been
//    invisible and the settings lost anyway. 1.80 is above it, and the migration finds them.
//
// The build number is upstream's 3621 - where this fork left it - plus the commits made since,
// 75 of them at 1.80. So it counts something real again instead of whatever a generator felt like,
// and it can be recomputed at any time:
//
//     git rev-list --count $(git merge-base HEAD origin/v1.78.2-dev)..HEAD
//
// It goes in the two versions people can see, and deliberately not in AssemblyVersion: that one
// names the settings folder, so tying it to the commit count would mint a new folder on every
// commit. The settings would follow now that the migration works, but they would be spread across
// a hundred folders for no reason.
//
// Nothing regenerates this file: the T4 transform is disabled on this branch so the project builds
// without a full Visual Studio. The numbers stay exactly as written until someone edits them.
[assembly: AssemblyVersion("1.80.0.0")]
[assembly: AssemblyFileVersion("1.80.0.3696")]
[assembly: NeutralResourcesLanguageAttribute("en-US")]
[assembly: AssemblyInformationalVersion("1.80 (Build 3696) x64")]