

//Generated for platform: x64

// This code was generated by a script. Any changes made manually will be lost
// the next time this code is regenerated.
//
// It is edited by hand here regardless, because the T4 transform that generates it does not run
// in this build: local-build-no-vs makes the TextTemplating import conditional so the project
// builds without a full Visual Studio, and the transform goes with it. AssemblyInfo.tt carries
// the same values, so a machine that does run the transform produces this same file.

using System.Reflection;
using System.Resources;

// Compute version values

//Build nr: 3621

// General Information
[assembly: AssemblyTitle("mRemoteNG")]
[assembly: AssemblyDescription("Multi-Remote Next Generation Connection Manager")]
[assembly: AssemblyConfiguration("x64")]
[assembly: AssemblyCompany("Profi-KOM Ltd.")]
[assembly: AssemblyProduct("mRemoteNG Connection Manager")]
[assembly: AssemblyCopyright("(c) 2026 mRemoteNG")]
[assembly: AssemblyTrademark("Profi-KOM LTd.")]
[assembly: AssemblyCulture("")]

// Version information
//
// AssemblyVersion is deliberately NOT the version shown to anyone. It is an identity: .NET keys
// the per-user settings store by it, under %LOCALAPPDATA%\<company>\<app>_Url_<hash>\<version>\.
// Moving it to 1.8.0.3621 on 2026-08-29 started the application in an empty store - it asked its
// first-run questions again and opened on a different monitor, because the window position lives
// there too. Nothing was lost, since the connections file is separate, but the settings were only
// a version folder away and would have looked gone.
//
// So the identity stays where it was, and the number people see moves instead: the splash and the
// About box read AssemblyInformationalVersion.
//
// To give this build a new number, edit the two lines below it and the informational version, and
// leave AssemblyVersion alone - all four parts of it, the last one included. That last part is the
// build number as well, and the settings folder is named after the whole four-part version, so
// moving it there resets the settings just as surely as moving the major does.
//
// Nothing regenerates this file here: the T4 transform is disabled on this branch so the project
// builds without a full Visual Studio. The numbers stay exactly as written until someone edits
// them, which is the point - they are release numbers now, not a clock.
[assembly: AssemblyVersion("1.78.2.3621")]
[assembly: AssemblyFileVersion("1.8.0.3621")]
[assembly: NeutralResourcesLanguageAttribute("en-US")]
[assembly: AssemblyInformationalVersion("1.8.0 (Build 3621) x64")]